// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/message/_middleware.ts";
import * as $3 from "./routes/api/message/index.ts";
import * as $4 from "./routes/api/message/listen.ts";
import * as $5 from "./routes/api/message/send.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/roadmap/index.tsx";
import * as $$0 from "./islands/Chat.tsx";
import * as $$1 from "./islands/ChatMessagesArea.tsx";
import * as $$2 from "./islands/SettingModal.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/message/_middleware.ts": $2,
    "./routes/api/message/index.ts": $3,
    "./routes/api/message/listen.ts": $4,
    "./routes/api/message/send.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/roadmap/index.tsx": $7,
  },
  islands: {
    "./islands/Chat.tsx": $$0,
    "./islands/ChatMessagesArea.tsx": $$1,
    "./islands/SettingModal.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
